<?php
/*
 * SWE40006 Deployment Portfolio Task 3
 * ------------------------------------
 * The directives added to or modified in wp-config.php across Tasks 3.2 and 3.3.
 *
 * This is a snippet, not a complete wp-config.php. Merge these into the file
 * generated by the WordPress installer, above the "That's all, stop editing!" comment
 */

/* -------------------------------------------------------------------------
 * Task 3.2 — Database decoupling to Amazon RDS
 * ---------------------------------------------------------------------- */

define( 'DB_NAME',     'wordpress_db' );
define( 'DB_USER',     'wp_user' );
define( 'DB_PASSWORD', '**********' ); //replace to password (redacted just for this document)

/*
 * DB_HOST is the RDS endpoint hostname only — no scheme, no port. RDS listens
 * on the MySQL default of 3306, which WordPress assumes.
 */
define( 'DB_HOST', 'REPLACE_WITH_RDS_ENDPOINT.ap-southeast-2.rds.amazonaws.com' );

/*
 * Required, and not part of a default WordPress configuration.
 *
 * Current RDS parameter groups set require_secure_transport = ON. WordPress
 * connects through PHP's mysqli extension, which does not negotiate TLS by
 * default, so without this constant the connection is refused by the engine
 * with MySQL error 3159 — surfaced to the user as a generic
 * Error establishing a database connection.
 *
 * If PHP cannot validate the server certificate, the flag below may be combined
 * with MYSQLI_CLIENT_SSL_DONT_VERIFY_SERVER_CERT. That still encrypts the
 * connection but skips hostname and CA validation, and should be documented as
 * a limitation if used:
 *
 *   define( 'MYSQL_CLIENT_FLAGS',
 *       MYSQLI_CLIENT_SSL | MYSQLI_CLIENT_SSL_DONT_VERIFY_SERVER_CERT );
 */
define( 'MYSQL_CLIENT_FLAGS', MYSQLI_CLIENT_SSL );

define( 'DB_CHARSET', 'utf8mb4' );
define( 'DB_COLLATE', '' );


/* -------------------------------------------------------------------------
 * Task 3.3 — Load balancing
 * ---------------------------------------------------------------------- */

/*
 * WordPress stores its canonical address in the database, in the wp_options
 * siteurl and home rows. Because every Auto Scaling Group instance shares
 * one RDS database, a stored instance IP would make all instances redirect
 * visitors to whichever instance was configured last.
 *
 * Defining these constants overrides the stored values at runtime. Because they
 * live in the configuration file, they are baked into the golden AMI and
 * inherited identically by every instance the ASG launches.
 */
define( 'WP_HOME',    'swe40006-alb-447325225.ap-southeast-2.elb.amazonaws.com' );
define( 'WP_SITEURL', 'swe40006-alb-447325225.ap-southeast-2.elb.amazonaws.com' );

/*
 * When an ALB terminates HTTPS it forwards plain HTTP to the target, so PHP
 * sees an insecure request and WordPress generates http:// URLs — producing
 * mixed-content warnings on an otherwise secure site.
 *
 * This makes the application aware of the client's original protocol. Included
 * now so that adding an HTTPS listener later requires no application change.
 */
if ( isset( $_SERVER['HTTP_X_FORWARDED_PROTO'] )
     && $_SERVER['HTTP_X_FORWARDED_PROTO'] === 'https' ) {
    $_SERVER['HTTPS'] = 'on';
}

/*
 * Optional hardening: prevents WordPress writing to its own source tree, which
 * matters for a golden-AMI deployment where any change written at runtime is
 * lost when the instance is replaced, giving the false impression that an
 * update succeeded.
 *
 * define( 'DISALLOW_FILE_EDIT', true );
 * define( 'DISALLOW_FILE_MODS', true );
 */

/* Authentication keys and salts are omitted from this repository by design.
 * Generate your own at https://api.wordpress.org/secret-key/1.1/salt/ */
